### PR TITLE
Pin Shape color and MenuBackground BlurEffect overrides added

### PR DESCRIPTION
**Pull request by keblodev**
Hey there!

In my project I need to have different color theme for menu than the default one.
So for better extensibility and reusability those 2 are required.

@arn00s please review once you'll have a chance
And btw menu is awesome :) found couple bugs -> will contribute to that later.
Thanks.

### CODE REVIEW

**Comment by zigzagg16** [comment]
Hello @ronanamsterdam , thanks for contributing ! I just miss some comments to approve your PR (I want to stay at 100% documentation coverage :) )

Thanks a lot ! 👍

**Comment by keblodev** [comment]
@arn00s ,
Got it. But not sure which comments I missed to add. Both ```getShapeColor() ``` and ```getBlurStyle()``` have them. Can you please comment on code?
Or maybe you can specify what document coverage tool you are using so I could run that to see what is missing?
*having that pointed out in README for contribution part -> would be helpful as well

Thanks.

**Comment by keblodev** [comment]
Found it.
This thing right?
https://github.com/realm/jazzy

gonna run that

**Comment by keblodev** [comment]
@arn00s,
I tried to run jazzy but for whatever reason I would not compile.
I have xcode 8.2.1 and my case ```xcodebuild``` works just fine from the console but ```jazzy``` fails every time with this:

```
> jazzy
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/yq/d1f2_0r50yb___75cjm6nplr0000gn/T/xcodebuild-F128B610-6784-450C-BEE6-981148ABFFD9.log
Failed to generate documentation
/Users/Fromrome/.rvm/gems/ruby-2.2.2/gems/jazzy-0.7.3/lib/jazzy/executable.rb:36:in `execute_command': /Users/Fromrome/.rvm/gems/ruby-2.2.2/gems/jazzy-0.7.3/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--module-name", "CariocaMenu", "--"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/yq/d1f2_0r50yb___75cjm6nplr0000gn/T/xcodebuild-F128B610-6784-450C-BEE6-981148ABFFD9.log

Failed to generate documentation
	from /Users/Fromrome/.rvm/gems/ruby-2.2.2/gems/jazzy-0.7.3/lib/jazzy/sourcekitten.rb:147:in `run_sourcekitten'
	from /Users/Fromrome/.rvm/gems/ruby-2.2.2/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:65:in `block in build'
	from /Users/Fromrome/.rvm/gems/ruby-2.2.2/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:63:in `chdir'
	from /Users/Fromrome/.rvm/gems/ruby-2.2.2/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:63:in `build'
	from /Users/Fromrome/.rvm/gems/ruby-2.2.2/gems/jazzy-0.7.3/bin/jazzy:15:in `<top (required)>'
	from /Users/Fromrome/.rvm/gems/ruby-2.2.2/bin/jazzy:23:in `load'
	from /Users/Fromrome/.rvm/gems/ruby-2.2.2/bin/jazzy:23:in `<main>'
	from /Users/Fromrome/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Fromrome/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

*meanwhile running jazzy on my own project -> worked just fine

So I either need the exact console line with arguments that you are using to generate the docs.
Or you commenting on what is missing in code on my PR -> would be the easiest option)

Spotted another small bug which is easy to fix, but blocked on pushing that till I get this one approved by you.

**Comment by zigzagg16** [comment]
Hello @ronanamsterdam , sorry for the mistake, I was viewing on a mobile phone. Indeed there are some issues with Jazzy, that I still need to fix.
Thanks for your work !

**Comment by keblodev** [comment]
sweet! gonna contribute some more :)
Thanks!

**Pull request merged**
